# Generated by Django 3.0 on 2020-01-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqArr', models.CharField(max_length=200)),
                ('allowedOperators', models.CharField(max_length=15)),
                ('negativeAnswerAllowed', models.BooleanField()),
                ('canExceedTen', models.BooleanField()),
            ],
        ),
    ]
