# Generated by Django 3.0 on 2020-01-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_defaultsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsettings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='allowedOperators',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='canExceedTen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='eqArr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='negativeAnswerAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
