# Generated by Django 3.0 on 2020-01-10 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_defaultsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqArr', models.CharField(default='(100, 200);(10,99)', max_length=200)),
                ('allowedOperators', models.CharField(default='+', max_length=4)),
                ('negativeAnswerAllowed', models.BooleanField(default=False)),
                ('canExceedTen', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DefaultSettings',
        ),
    ]
