# Generated by Django 3.0 on 2020-01-09 05:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200109_0528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultSettings',
            new_name='DefaultSetting',
        ),
    ]
