# Generated by Django 3.0 on 2020-01-09 05:53

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200109_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsetting',
            name='allowedOperators',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='defaultsetting',
            name='eqArr',
            field=models.CharField(default='(100, 200);(10,99)', max_length=200),
        ),
    ]
