# Generated by Django 3.0 on 2020-01-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200109_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsetting',
            name='allowedOperators',
            field=models.CharField(default='+', max_length=4),
        ),
    ]
