# Generated by Django 3.0 on 2020-01-12 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='user_did',
        ),
        migrations.CreateModel(
            name='ChoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.Chore')),
                ('user_did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_did', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
