# Generated by Django 3.0 on 2020-01-12 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0002_auto_20200112_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='user_assign',
        ),
        migrations.AddField(
            model_name='chore',
            name='user_assign',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
