# Generated by Django 3.0 on 2020-01-12 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0003_auto_20200112_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorelog',
            name='user_did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_chore', to=settings.AUTH_USER_MODEL),
        ),
    ]
