# Generated by Django 3.0 on 2020-01-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_auto_20200112_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorelog',
            name='chore_name',
        ),
        migrations.AddField(
            model_name='chorelog',
            name='chore_name',
            field=models.ManyToManyField(to='chores.Chore'),
        ),
    ]
