# Generated by Django 3.0 on 2020-01-12 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0005_auto_20200112_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorelog',
            name='user_did',
        ),
        migrations.AddField(
            model_name='chorelog',
            name='user_did',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
