# Generated by Django 3.0 on 2020-01-12 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0006_auto_20200112_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorelog',
            name='chore_name',
        ),
        migrations.AddField(
            model_name='chorelog',
            name='chore_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chores.Chore'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chorelog',
            name='user_did',
        ),
        migrations.AddField(
            model_name='chorelog',
            name='user_did',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='log_chore', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
