# Generated by Django 3.0 on 2020-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_auto_20200112_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='done_last',
        ),
        migrations.AddField(
            model_name='chorelog',
            name='done_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
