# Generated by Django 3.1 on 2020-09-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_auto_20200112_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='image',
            field=models.ImageField(default='cat.png', upload_to='chore_images'),
        ),
    ]
