# Generated by Django 3.1 on 2020-09-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_auto_20200912_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='image',
            field=models.ImageField(default='cat.png', upload_to='chore_images'),
        ),
    ]
