# Generated by Django 3.1 on 2020-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_auto_20200912_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='show_by_image',
            field=models.BooleanField(default=False),
        ),
    ]
