# Generated by Django 3.1 on 2020-09-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0012_chore_show_by_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='duration',
        ),
    ]
