# Generated by Django 3.0 on 2019-12-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1Max', models.IntegerField()),
                ('num2Max', models.IntegerField()),
                ('add', models.BooleanField()),
                ('subtract', models.BooleanField()),
                ('multiply', models.BooleanField()),
                ('divide', models.BooleanField()),
            ],
        ),
    ]
