# Generated by Django 3.0 on 2020-01-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20200103_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score',
        ),
    ]
